---

services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui/src:/app/src
      - ./ui/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend

  backend:
    build:
      context: ./svc
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST: mysql
      - MYSQL_DATABASE: ${MYSQL_DB}
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE: my${MYSQL_DB}
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  mysql-data:
